# Generated by Django 2.2.5 on 2019-09-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radcheck',
            name='description2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
