# Generated by Django 2.2.5 on 2019-09-07 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_radcheck_description2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radcheck',
            name='description',
        ),
        migrations.RemoveField(
            model_name='radcheck',
            name='description2',
        ),
    ]
