# Generated by Django 2.2.5 on 2019-09-07 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stations', '0004_radcheck_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='radcheck',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='radcheck',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='radcheck',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
