# Generated by Django 2.2.5 on 2019-09-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0005_auto_20190907_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radcheck',
            name='mac',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
